CREATE DATABASE ikualoApp;
USE ikualoApp;


CREATE TABLE user (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(20) NOT NULL,
lastname VARCHAR(80) NOT NULL,
email VARCHAR(75) NOT NULL UNIQUE,
password VARCHAR(100) NOT NULL,
is_deleted BOOLEAN default 0
);

SELECT * FROM user;